# Generated by Django 2.1.7 on 2019-04-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_attribute_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='type_attribute',
            field=models.ManyToManyField(blank=True, null=True, related_name='attribute', to='product.Product'),
        ),
    ]
