# Generated by Django 2.1.7 on 2019-04-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20190417_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='type_attribute',
            field=models.ManyToManyField(related_name='attribute', to='product.Product'),
        ),
    ]
