# Generated by Django 2.1.7 on 2019-05-20 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20190417_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='type_attribute',
        ),
        migrations.AddField(
            model_name='attribute',
            name='type_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute', to='product.Product'),
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='attribute',
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_value', to='product.Attribute'),
        ),
    ]
