# Generated by Django 2.1.7 on 2019-06-03 07:58

import django.contrib.postgres.fields.hstore
from django.db import migrations
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20190521_1044'),
    ]

    operations = [
        HStoreExtension(),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict),
        ),
    ]
