# Generated by Django 2.1.7 on 2020-01-23 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0008_auto_20200123_1859'),
        ('product', '0017_auto_20190731_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='discount.Sale'),
        ),
    ]
