# Generated by Django 2.1.7 on 2020-01-27 13:49

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_product_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, verbose_name='Video'),
        ),
    ]
