# Generated by Django 2.1.7 on 2020-01-22 18:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_auto_20200122_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 22, 18, 15, 3, 269540, tzinfo=utc)),
        ),
    ]
