# Generated by Django 2.1.7 on 2020-01-23 05:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_auto_20200122_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 23, 5, 24, 21, 458741, tzinfo=utc)),
        ),
    ]
