# Generated by Django 2.1.7 on 2020-01-23 17:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0004_auto_20200123_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 23, 17, 31, 48, 917597, tzinfo=utc)),
        ),
    ]
