# Generated by Django 2.1.7 on 2020-01-27 05:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0010_auto_20200125_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 27, 5, 24, 10, 297950, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 27, 5, 24, 10, 298904, tzinfo=utc)),
        ),
    ]
