# Generated by Django 2.1.7 on 2020-01-28 17:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0013_auto_20200128_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 28, 17, 16, 35, 356064, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 28, 17, 16, 35, 356817, tzinfo=utc)),
        ),
    ]
