# Generated by Django 2.1.7 on 2020-01-29 05:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0014_auto_20200128_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 29, 5, 24, 37, 556518, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 29, 5, 24, 37, 557439, tzinfo=utc)),
        ),
    ]
