# Generated by Django 2.0.4 on 2019-01-23 07:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0005_auto_20181006_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='productincart',
            options={},
        ),
        migrations.RemoveField(
            model_name='productincart',
            name='created',
        ),
        migrations.RemoveField(
            model_name='productincart',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productincart',
            name='nmb',
        ),
        migrations.RemoveField(
            model_name='productincart',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productincart',
            name='price_per_item',
        ),
        migrations.RemoveField(
            model_name='productincart',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='productincart',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='productincart',
            name='updated',
        ),
        migrations.AddField(
            model_name='productincart',
            name='quantity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='productincart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='productincart',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_in_cart', to='order.Cart'),
        ),
    ]
