# Generated by Django 2.0.4 on 2019-02-07 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderline',
            old_name='qauntity',
            new_name='quantity',
        ),
    ]
