# Generated by Django 2.0.4 on 2019-02-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20190207_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
