# Generated by Django 2.1.7 on 2020-01-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_orderline_sub_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
    ]
